// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3JoxKrY9B-eL7eCktuMMPT7A4Lux5yUw',
    appId: '1:388243556134:web:2226d80ff3175583ad63e7',
    messagingSenderId: '388243556134',
    projectId: 'hotels-2e2e2',
    authDomain: 'hotels-2e2e2.firebaseapp.com',
    storageBucket: 'hotels-2e2e2.appspot.com',
    measurementId: 'G-NM5LGPB7CF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTnBP45NcYFairwmtkYO96NKz1W-1K30o',
    appId: '1:388243556134:android:9f87b2496e97a197ad63e7',
    messagingSenderId: '388243556134',
    projectId: 'hotels-2e2e2',
    storageBucket: 'hotels-2e2e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzPMr-XZyp-v4nFUjQuxgyuiDHeB_pQ6o',
    appId: '1:388243556134:ios:f1857f7bb0c06af3ad63e7',
    messagingSenderId: '388243556134',
    projectId: 'hotels-2e2e2',
    storageBucket: 'hotels-2e2e2.appspot.com',
    iosBundleId: 'com.example.hotels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzPMr-XZyp-v4nFUjQuxgyuiDHeB_pQ6o',
    appId: '1:388243556134:ios:f1857f7bb0c06af3ad63e7',
    messagingSenderId: '388243556134',
    projectId: 'hotels-2e2e2',
    storageBucket: 'hotels-2e2e2.appspot.com',
    iosBundleId: 'com.example.hotels',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3JoxKrY9B-eL7eCktuMMPT7A4Lux5yUw',
    appId: '1:388243556134:web:08501b9058450743ad63e7',
    messagingSenderId: '388243556134',
    projectId: 'hotels-2e2e2',
    authDomain: 'hotels-2e2e2.firebaseapp.com',
    storageBucket: 'hotels-2e2e2.appspot.com',
    measurementId: 'G-0K2DLD6LF8',
  );

}